import Monaliza from "../src/assets/welcomeimage1661254149_256.jpg";
import David from "../src/assets/davidcover1661254508_256.jpg";
import Sogreat from "../src/assets/sogreat1661259325_256.jpg";
import Europ from "../src/assets/european-man-woman-casual-wear-standing-back-back-with-arms-crossed-isolated-colorful-wall_171337-51292.jpg";
import Emd from "../src/assets/Diamond.png";
import Jack from "../src/assets/jack.jpeg";

const chapterItems = [
  {
    chapterId: 1,
    lessonId: 1,
    completed: true,
    imgSrc: Monaliza,
    mainText: "تقديم نفسك",
    subText: "تعلم التحية عند مقابلة الأشخاص",
    url: "/test/chapter1",
  },
  {
    chapterId: 1,
    lessonId: 2,
    completed: false,
    imgSrc: David,
    mainText: "تقديم نفسك",
    subText: "قل اسمك",
    url: "/test/chapter2",
  },
  {
    chapterId: 1,
    lessonId: 3,
    completed: false,
    imgSrc: Sogreat,
    mainText: "القول كيف أنت",
    subText: "تحدث عن كيف تشعر",
    url: "/test/chapter3",
  },
  {
    chapterId: 1,
    lessonId: 4,
    completed: false,
    imgSrc: Europ,
    mainText: "تطوير الطلاقة",
    subText: "عرِّف عن نفسك",
    url: "/test/chapter4",
  },
  {
    chapterId: 1,
    lessonId: 5,
    completed: false,
    type: "checkpoint",
    imgSrc: Emd,
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "/test/chapter5",
  },
  {
    chapterId: 2,
    lessonId: 1,
    completed: false,
    imgSrc: Jack,
    mainText: "السؤال عن الآخرين",
    subText: "تعلم كيفية السؤال عن مشاعر الأشخاص الآخرين",
    url: "/test/chapter6",
  },
  {
    completed: false,
    imgSrc: David,
    mainText: "قول أين تعيش",
    subText: "تحدث عن المكان الذي تعيش فيه",
    url: "/test/chapter7",
    chapterId: 2,
    lessonId: 2,
  },
  {
    completed: false,
    imgSrc: Sogreat,
    mainText: "إعطاء جنسيتك",
    subText: "تعلم كيفية القول من أي دولة أنت",
    url: "/test/chapter8",
    chapterId: 2,
    lessonId: 3,
  },
  {
    completed: false,
    imgSrc: Europ,
    mainText: "إنهاء المحادثة",
    subText: "تعلم كيفية إنهاء المحادثة",
    url: "/test/chapter9",
    chapterId: 2,
    lessonId: 4,
  },
  {
    completed: false,
    type: "checkpoint",
    imgSrc: Emd,
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "/test/chapter10",
    chapterId: 2,
    lessonId: 5,
  },
  {
    completed: false,
    imgSrc: Jack,
    mainText: "إنهاء المحادثة",
    subText: "تعلم كيفية إنهاء المحادثة",
    url: "/test/chapter6",
    chapterId: 3,
    lessonId: 1,
  },
  {
    completed: false,
    imgSrc: David,
    mainText: "إنهاء المحادثة",
    subText: "تعلم كيفية إنهاء المحادثة",
    url: "/test/chapter7",
    chapterId: 3,
    lessonId: 2,
  },
  {
    completed: false,
    imgSrc: Sogreat,
    mainText: "إنهاء المحادثة",
    subText: "تعلم كيفية إنهاء المحادثة",
    url: "/test/chapter8",
    chapterId: 3,
    lessonId: 3,
  },
  {
    completed: false,
    imgSrc: Europ,
    mainText: "إنهاء المحادثة",
    subText: "تعلم كيفية إنهاء المحادثة",
    url: "/test/chapter9",
    chapterId: 3,
    lessonId: 4,
  },
  {
    completed: false,
    type: "checkpoint",
    imgSrc: Emd,
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "/test/chapter10",
    chapterId: 3,
    lessonId: 5,
  },
  {
    completed: false,
    imgSrc: Jack,
    mainText: "إنهاء المحادثة",
    subText: "تعلم كيفية إنهاء المحادثة",
    url: "/test/chapter6",
    chapterId: 4,
    lessonId: 1,
  },
  {
    completed: false,
    imgSrc: David,
    mainText: "إنهاء المحادثة",
    subText: "تعلم كيفية إنهاء المحادثة",
    url: "/test/chapter7",
    chapterId: 4,
    lessonId: 2,
  },
  {
    completed: false,
    imgSrc: Sogreat,
    mainText: "إنهاء المحادثة",
    subText: "تعلم كيفية إنهاء المحادثة",
    url: "/test/chapter8",
    chapterId: 4,
    lessonId: 3,
  },
  {
    completed: false,
    imgSrc: Europ,
    mainText: "إنهاء المحادثة",
    subText: "تعلم كيفية إنهاء المحادثة",
    url: "/test/chapter9",
    chapterId: 4,
    lessonId: 4,
  },
  {
    completed: false,
    type: "checkpoint",
    imgSrc: Emd,
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "/test/chapter10",
    chapterId: 4,
    lessonId: 5,
  },
];

export default chapterItems;
