import React from "react";
import {
  ProjectAnswerBlockButton,
  ProjectAnswerBlockButtonSpanOne,
  ProjectAnswerBlockButtonSpanTwo,
  ProjectAnswerBlockButtonSubSpanTwo,
  ProjectAnswerBlockContainer,
  ProjectAnswerBlockSpan,
  ProjectAnswerContainer,
  ProjectAnswerContainerBottom,
  ProjectAnswerSubContainer,
  ProjectAnswerSubContainerBottom,
  ProjectAnswerSubContainerTop,
  ProjectAnswerSubTopLine,
  ProjectAnswerTopArea,
  ProjectAnswerTopLi,
  ProjectAnswerTopSpaceCont,
  ProjectAnswerTopSpaceReCont,
  ProjectBorder,
  ProjectContainer,
  ProjectLanguageContainer,
  ProjectLanguageImgCanvas,
  ProjectLanguageImgCanvasContainer,
  ProjectLanguageImgContainer,
  ProjectLanguageSouFirstDiv,
  ProjectLanguageSouFirstSpan,
  ProjectLanguageSoundButtonSpan,
  ProjectLanguageSoundButtonSvg,
  ProjectLanguageSoundFirst,
  ProjectLanguageSoundFirstButton,
  ProjectLanguageSoundFirstSpan,
  ProjectLanguageSoundSec,
  ProjectLanguageSoundSubFirst,
  ProjectLanguageSoundWrapper,
  ProjectLanguageSubContainer,
  ProjectLanguageSubWrapper,
  ProjectSecStart,
  ProjectSecStartContainer,
  ProjectSecStartWrapper,
  ProjectStart,
  ProjectStartHeader,
  ProjectStartSpan,
  ProjectSubContainer,
  ProjectSubStart,
  ProjectWrapper,
} from "./Project.elements";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faVolumeHigh } from "@fortawesome/free-solid-svg-icons";
import Dude from "../../assets/dude.png";

const Project = () => {
  return (
    <ProjectWrapper>
      <ProjectContainer>
        <ProjectSubContainer>
          <ProjectBorder>
            <ProjectStart>
              <ProjectSubStart>
                <ProjectStartHeader>
                  <ProjectStartSpan>
                    اكتب ما يلي باللغة العربية:
                  </ProjectStartSpan>
                </ProjectStartHeader>
              </ProjectSubStart>
              <ProjectSecStart>
                <ProjectSecStartContainer>
                  <ProjectLanguageContainer>
                    <ProjectLanguageSubContainer>
                      <ProjectLanguageImgContainer>
                        <ProjectLanguageImgCanvas src={Dude} />
                      </ProjectLanguageImgContainer>
                    </ProjectLanguageSubContainer>
                    <ProjectLanguageSubWrapper>
                      <ProjectLanguageSoundWrapper>
                        <ProjectLanguageSoundFirst>
                          <ProjectLanguageSoundSubFirst>
                            <ProjectLanguageSoundFirstSpan>
                              <ProjectLanguageSoundFirstButton>
                                <ProjectLanguageSoundButtonSpan>
                                  <ProjectLanguageSoundButtonSvg>
                                    <FontAwesomeIcon icon={faVolumeHigh} />
                                  </ProjectLanguageSoundButtonSvg>
                                </ProjectLanguageSoundButtonSpan>
                              </ProjectLanguageSoundFirstButton>
                            </ProjectLanguageSoundFirstSpan>
                            <ProjectLanguageSouFirstSpan>
                              <ProjectLanguageSouFirstDiv>
                                water
                              </ProjectLanguageSouFirstDiv>
                            </ProjectLanguageSouFirstSpan>
                          </ProjectLanguageSoundSubFirst>
                        </ProjectLanguageSoundFirst>
                        <ProjectLanguageSoundSec></ProjectLanguageSoundSec>
                      </ProjectLanguageSoundWrapper>
                    </ProjectLanguageSubWrapper>
                  </ProjectLanguageContainer>
                </ProjectSecStartContainer>
                <ProjectSecStartWrapper>
                  <ProjectAnswerContainer>
                    <ProjectAnswerSubContainer>
                      <ProjectAnswerSubContainerTop>
                        <ProjectAnswerSubTopLine>
                          <ProjectAnswerTopLi>
                            <ProjectAnswerTopSpaceCont>
                              <ProjectAnswerTopArea></ProjectAnswerTopArea>
                              <ProjectAnswerTopArea></ProjectAnswerTopArea>
                              <ProjectAnswerTopArea></ProjectAnswerTopArea>
                              <ProjectAnswerTopArea></ProjectAnswerTopArea>
                            </ProjectAnswerTopSpaceCont>
                            <ProjectAnswerTopSpaceReCont></ProjectAnswerTopSpaceReCont>
                          </ProjectAnswerTopLi>
                        </ProjectAnswerSubTopLine>
                      </ProjectAnswerSubContainerTop>
                      <ProjectAnswerSubContainerBottom>
                        <ProjectAnswerContainerBottom>
                          <ProjectAnswerBlockContainer>
                            <ProjectAnswerBlockSpan>
                              <ProjectAnswerBlockButton>
                                <ProjectAnswerBlockButtonSpanOne></ProjectAnswerBlockButtonSpanOne>
                                <ProjectAnswerBlockButtonSpanTwo>
                                  <ProjectAnswerBlockButtonSubSpanTwo>
                                    رجل
                                  </ProjectAnswerBlockButtonSubSpanTwo>
                                </ProjectAnswerBlockButtonSpanTwo>
                              </ProjectAnswerBlockButton>
                            </ProjectAnswerBlockSpan>
                          </ProjectAnswerBlockContainer>
                          <ProjectAnswerBlockContainer>
                            <ProjectAnswerBlockSpan>
                              <ProjectAnswerBlockButton>
                                <ProjectAnswerBlockButtonSpanOne></ProjectAnswerBlockButtonSpanOne>
                                <ProjectAnswerBlockButtonSpanTwo>
                                  <ProjectAnswerBlockButtonSubSpanTwo>
                                    الرجل
                                  </ProjectAnswerBlockButtonSubSpanTwo>
                                </ProjectAnswerBlockButtonSpanTwo>
                              </ProjectAnswerBlockButton>
                            </ProjectAnswerBlockSpan>
                          </ProjectAnswerBlockContainer>
                          <ProjectAnswerBlockContainer>
                            <ProjectAnswerBlockSpan>
                              <ProjectAnswerBlockButton>
                                <ProjectAnswerBlockButtonSpanOne></ProjectAnswerBlockButtonSpanOne>
                                <ProjectAnswerBlockButtonSpanTwo>
                                  <ProjectAnswerBlockButtonSubSpanTwo>
                                    ماء
                                  </ProjectAnswerBlockButtonSubSpanTwo>
                                </ProjectAnswerBlockButtonSpanTwo>
                              </ProjectAnswerBlockButton>
                            </ProjectAnswerBlockSpan>
                          </ProjectAnswerBlockContainer>
                          <ProjectAnswerBlockContainer>
                            <ProjectAnswerBlockSpan>
                              <ProjectAnswerBlockButton>
                                <ProjectAnswerBlockButtonSpanOne></ProjectAnswerBlockButtonSpanOne>
                                <ProjectAnswerBlockButtonSpanTwo>
                                  <ProjectAnswerBlockButtonSubSpanTwo>
                                    اشرب
                                  </ProjectAnswerBlockButtonSubSpanTwo>
                                </ProjectAnswerBlockButtonSpanTwo>
                              </ProjectAnswerBlockButton>
                            </ProjectAnswerBlockSpan>
                          </ProjectAnswerBlockContainer>
                          <ProjectAnswerBlockContainer>
                            <ProjectAnswerBlockSpan>
                              <ProjectAnswerBlockButton>
                                <ProjectAnswerBlockButtonSpanOne></ProjectAnswerBlockButtonSpanOne>
                                <ProjectAnswerBlockButtonSpanTwo>
                                  <ProjectAnswerBlockButtonSubSpanTwo>
                                    التفاحة
                                  </ProjectAnswerBlockButtonSubSpanTwo>
                                </ProjectAnswerBlockButtonSpanTwo>
                              </ProjectAnswerBlockButton>
                            </ProjectAnswerBlockSpan>
                          </ProjectAnswerBlockContainer>
                        </ProjectAnswerContainerBottom>
                      </ProjectAnswerSubContainerBottom>
                    </ProjectAnswerSubContainer>
                  </ProjectAnswerContainer>
                </ProjectSecStartWrapper>
              </ProjectSecStart>
            </ProjectStart>
          </ProjectBorder>
        </ProjectSubContainer>
      </ProjectContainer>
    </ProjectWrapper>
  );
};

export default Project;
